### ISSUE TITLE
Domaine Catalina

### ISSUE THREAD

**Issue by arthaud-proust** [les-voix-errantes-de-kyiv/4-catalina#1]
# Configuration du sous domaine de votre projet

- [x] Ajoutez "4-catalina.les-voix-errantes-de-kyiv.fr" en tant que nom de domaine sur votre hébergeur (vercel, netlify, etc)

- [x] **Répondez ci-dessous quel hébergeur vous utilisez pour que je fasse pointer le domaine dessus.**

Dispo pour toute question

**Comment by arthaud-proust** [comment]
Hébergeur : vercel

**Comment by arthaud-proust** [comment]
Tout est bon ! Merci !

**Comment by arthaud-proust** [comment]
Hello,
Vous pouvez ajouter le nom de domaine `catalina.les-voix-errantes-de-kyiv.fr` dans votre hébergeur.
L'ancienne adresse redirigera vers la nouvelle, comme ça si vous avez fait un qr code il fonctionnera toujours.

**Comment by mthibaultweb** [comment]
Hola,
J'ai à nouveau une erreur lors de l'ajout des sous-domaines :
_Another Vercel account is using this domain. Please set the following TXT record on _vercel.les-voix-errantes-de-kyiv.fr to use catalina.les-voix-errantes-de-kyiv.fr in this project. Once the verification is completed and the domain is successfully configured, the TXT record can be removed._

Type : TXT
Name : _vercel
Value :
vc-domain-verify=catalina.les-voix-errantes-de-kyiv.fr,f2877ede4d000ed304f7

**Comment by arthaud-proust** [comment]
Salut Maxime,
J'ai ajouté le record, merci pour le message détaillé !
Dis-moi si ça fonctionne
